# Generated by Django 4.0.4 on 2022-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_payment_created_alter_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ManyToManyField(to='bakery.product'),
        ),
    ]
