# Generated by Django 4.0.4 on 2022-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0017_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(default='', max_length=100),
        ),
    ]
