# Generated by Django 4.0.4 on 2022-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0019_remove_product_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(default='', max_length=100),
        ),
    ]
