# Generated by Django 4.0.4 on 2022-06-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0023_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
