# Generated by Django 4.0.4 on 2022-06-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0026_rename_no_of_items_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
