# Generated by Django 4.0.4 on 2022-06-12 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0027_remove_order_product_order_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderPlaced',
        ),
    ]
